// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe7XUVDAS5AIRjEGruW9exIRPcSdDmbFU',
    appId: '1:232445123017:web:70446d3f75022ebf093018',
    messagingSenderId: '232445123017',
    projectId: 'flutter-ecom-uesr-app',
    authDomain: 'flutter-ecom-uesr-app.firebaseapp.com',
    storageBucket: 'flutter-ecom-uesr-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbksye86LqG3oXwsar-T65X-K41QujyWY',
    appId: '1:232445123017:android:ae93fd3f35b8ac15093018',
    messagingSenderId: '232445123017',
    projectId: 'flutter-ecom-uesr-app',
    storageBucket: 'flutter-ecom-uesr-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAehMHn4liI1uFxM3eB2j5ZXTUxPGCHadY',
    appId: '1:232445123017:ios:762dbb54b312ffd9093018',
    messagingSenderId: '232445123017',
    projectId: 'flutter-ecom-uesr-app',
    storageBucket: 'flutter-ecom-uesr-app.appspot.com',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAehMHn4liI1uFxM3eB2j5ZXTUxPGCHadY',
    appId: '1:232445123017:ios:763363ff4f34bfde093018',
    messagingSenderId: '232445123017',
    projectId: 'flutter-ecom-uesr-app',
    storageBucket: 'flutter-ecom-uesr-app.appspot.com',
    iosBundleId: 'com.example.eCom.RunnerTests',
  );
}
